cache:
  directories:
    - node_modules
    - ~/.npm
deploy:
  commit_message: "Deploy del proyecto"
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/
  provider: pages
  skip_cleanup: true
  target_branch: gh-page
  true:
    branch: master
git:
  depth: 3
lenguage: node_js
node_js:
  - "12"
script:
  - "yarn build"
